In [1]:
import os, sys

In [2]:
os.environ['LD_LIBRARY_PATH']

'/home/yhc/cuda/lib64:/home/yhc/cuda/lib64:/usr/local/cuda-11.2/lib64'

In [3]:
sys.version

'3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]'

In [4]:
import tensorflow as tf

In [5]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [6]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [7]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [8]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [9]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.97273445, -0.43674985,  1.2031113 , -0.5078096 ,  0.336805  ,
        -0.1773164 , -0.523349  , -0.09237707,  0.19756557, -0.34940365]],
      dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.20522049, 0.05012905, 0.2583879 , 0.04669051, 0.1086526 ,
        0.06497706, 0.04597058, 0.07073733, 0.0945299 , 0.05470455]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.7337213

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 774us/step - loss: 0.0676 - accuracy: 0.9781
Epoch 2/5
1875/1875 [==============================] - 1s 751us/step - loss: 0.0566 - accuracy: 0.9816
Epoch 3/5
1875/1875 [==============================] - 1s 761us/step - loss: 0.0505 - accuracy: 0.9830
Epoch 4/5
1875/1875 [==============================] - 1s 759us/step - loss: 0.0484 - accuracy: 0.9840
Epoch 5/5
1875/1875 [==============================] - 1s 782us/step - loss: 0.0433 - accuracy: 0.9855


In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0692 - accuracy: 0.9801


[0.06915415823459625, 0.9800999760627747]

In [18]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [19]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.9224424e-09, 2.7981445e-10, 4.8034028e-08, 5.5454807e-06,
        1.3780999e-15, 4.3559631e-09, 5.5340194e-16, 9.9999273e-01,
        1.1331804e-09, 1.6953311e-06],
       [4.9707370e-11, 1.0166681e-06, 9.9999893e-01, 2.4016316e-09,
        8.8493438e-21, 4.8074789e-10, 2.8469588e-13, 7.0688465e-18,
        1.5991901e-10, 5.2412509e-18],
       [3.5844396e-09, 9.9996102e-01, 4.7309800e-06, 4.4151321e-08,
        2.2524669e-06, 7.1495236e-08, 3.6391472e-07, 5.1631559e-06,
        2.6360702e-05, 1.0628582e-08],
       [9.9995124e-01, 4.7366434e-12, 1.1815267e-05, 2.1688255e-08,
        3.6079882e-08, 1.5826548e-07, 2.1270857e-06, 2.8465982e-07,
        1.2228385e-11, 3.4388402e-05],
       [1.9383084e-07, 6.1976661e-13, 6.7971960e-06, 7.3856704e-10,
        9.9953544e-01, 3.9645629e-09, 5.6011686e-08, 7.1444873e-07,
        9.8633883e-09, 4.5679326e-04]], dtype=float32)>